# Generated by Django 5.0.6 on 2024-06-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_userfile_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='user_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
